### ISSUE TITLE
Is it broken?

### ISSUE THREAD

**Issue by AlexWayfer** [Richard87/releaser#13]
Hello!

Links from email:
*   Hi Alexander Popov, [keeweb/keeweb](http://email.richardhagen.no/c/eJw9jcsOwiAURL-mLBvkUWDBwk3_49I7tMRWTYup_r24MZnFzMlJhqOS8IMoUZvE2cG4QGyz9C4g6EYUMoK7yM7I4yy59jPu2KmCxRIxsYdT2TbbU7B2MKwDa8MuuAQSa1xqfR6dvnZqbJlLXV6pnx5bGzfgRPoXsUda8e5P-mTs7W_eqKw_9wtRkzRH) have just released a new update
*   Check it out here: [Desktop apps v1.5.1](http://email.richardhagen.no/c/eJxNjjsOwyAAQ08TRkT4BBgYuvQefAyJmn4EtGlvX7pVsqxnD5aT4wxmIZsTMqSsIbX1SWVmtIUVo-HIsHpmk2Tt2HKnBTdU35HI6sAXtaTIdOawNlkhwc0iTDQhBqUi2d3a-6NN4jTx81DZ-voMNN6vI1yAA-EfKnb4hjaw-zL8NVNFZ1Kd3_Gmh_9k1PGkXP22_1a-zT072Q)

All of them redirects to http://www.create-it.no/

And https://releaser.richardhagen.no/ :

![image](https://cloud.githubusercontent.com/assets/6510020/26376567/9e0fbb76-4015-11e7-8e98-43c8dfd05be1.png)

😱

**Comment by Richard87** [comment]
Hi, no, unfortunatly my domain name service tried to raise the price by 2.5
times (UniWeb in norway!) So I had to change the service provider...
Because of DNSSEC there might be some issues with the domain name the next
2 days (create-it.no is another domain of mine)...

But rest asured, within 36 hours now, everything should be sorted :)

Richard

tir. 23. mai 2017 kl. 23:12 skrev Alexander Popov <notifications@github.com

**Comment by AlexWayfer** [comment]
Okay, thanks!

**Comment by AlexWayfer** [comment]
Already passed almost 72 hours, but the problem remained :cry:

Google DNS (`8.8.8.8`, `8.8.8.4`).

**Comment by Richard87** [comment]
Sorry, I missunderstood the issue, it has been fixed now, but it will take aprox. 2 hours before the DNS is properly updated...

(Theh issue was the MailGun's redirect url, email.richardhagen.no was not copied when I changed the registrar for my domain :-1:  )

**Comment by AlexWayfer** [comment]
Thanks! I saw your respond for #14, just checked — everything works :+1:

**Comment by Richard87** [comment]
Thanks!
